name: Release artifacts from Quester repository

on:
  push:
    tags:
      - "v*"

jobs:
  release-macos-artifacts:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin, 'x86_64-unknown-linux-gnu']

    steps:
      - run: echo "ASSET_FULL_NAME=querent-${{ github.ref }}-${{ matrix.target }}" >> $GITHUB_ENV
      - name: Download Release Artifacts for ${{ matrix.target }} and version ${{ github.ref }}
        run: |
          wget --header="Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" -O ${{ env.ASSET_FULL_NAME }}.tar.gz https://api.github.com/repos/querent-ai/quester/releases/assets/$(curl -s https://api.github.com/repos/querent-ai/quester/releases/tags/${{ github.ref }} | jq -r '.assets[] | select(.name == env.ASSET_FULL_NAME + ".tar.gz") | .id')
          echo "Downloaded artifacts for ${{ matrix.target }} and version ${{ github.ref }}"
      - name: Upload Release Artifacts for ${{ matrix.target }} and version ${{ github.ref }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ASSET_FULL_NAME }}
          path: ${{ env.ASSET_FULL_NAME }}.tar.gz
      - name: Upload archive
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          overwrite: true
          tag_name: ${{ github.ref }}
