name: Release artifacts from Quester repository

on:
  push:
    tags:
      - "v*"

jobs:
  release-macos-artifacts:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin, 'x86_64-unknown-linux-gnu', 'x86_64-pc-windows-msvc.exe']

    steps:
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "ASSET_FULL_NAME=querent-${{ env.ASSET_VERSION }}-${{ matrix.target }}" >> $GITHUB_ENV
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/quester"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          target: ${{ env.ASSET_FULL_NAME }}.tar.gz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload Release Artifacts for ${{ matrix.target }} and version ${{ github.ref }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ASSET_FULL_NAME }}
          path: ${{ env.ASSET_FULL_NAME }}.tar.gz
      - name: Upload archive
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
