name: Release artifacts from Querent Production repository

on:
  push:
    tags:
      - "v*"

jobs:
  release-querent-binary-artifacts:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-apple-darwin,
            aarch64-apple-darwin,
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc.exe,
          ]

    steps:
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "ASSET_FULL_NAME=rian-${{ env.ASSET_VERSION }}-${{ matrix.target }}" >> $GITHUB_ENV
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          target: ${{ env.ASSET_FULL_NAME }}.tar.gz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload binaries assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}

  release-querent-windows-installer:
    name: Build Windows Installer
    runs-on: ubuntu-latest
    steps:
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Download update.json
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: "update.json"
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload update.json to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "update.json"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Download Windows Installer(s)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.msi"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Renaming .msi file to rian-windows-${{ env.ASSET_VERSION }}.msi
        run: mv *.msi rian-windows-${{ env.ASSET_VERSION }}.msi
      - name: Upload Windows Installer(s) to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "rian-windows-${{ env.ASSET_VERSION }}.msi"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Download Linux Installer(s)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.AppImage"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Renaming .AppImage file to rian-linux-${{ env.ASSET_VERSION }}.AppImage
        run: mv *.AppImage rian-linux-${{ env.ASSET_VERSION }}.AppImage
      - name: Upload Linux Installer(s) to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "rian-linux-${{ env.ASSET_VERSION }}.AppImage"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Download MacOS Installer(s)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.tar.gz"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload MacOS Installer(s) to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "rian.app.tar.gz;aarch64-rian.app.tar.gz"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Download All .sig files
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.sig"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload All .sig files to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ".*\\.sig"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
