name: Release artifacts from Querent Production repository

on:
  push:
    tags:
      - "v*"

jobs:
  release-querent-binary-artifacts:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-apple-darwin,
            aarch64-apple-darwin,
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc.exe,
          ]

    steps:
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "ASSET_FULL_NAME=rian-${{ env.ASSET_VERSION }}-${{ matrix.target }}" >> $GITHUB_ENV
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          target: ${{ env.ASSET_FULL_NAME }}.tar.gz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload binaries assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}

  release-querent-rian-installers:
    name: Build installers
    runs-on: ubuntu-latest
    steps:
      - name: Extract .AppImage File
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.AppImage"  # Valid regex pattern
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload .AppImage assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.AppImage"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Extract .AppImage.sig File
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.AppImage\\.sig"  # Valid regex pattern
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload .AppImage.sig assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.AppImage.sig"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Extract .msi File
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.msi"  # Valid regex pattern
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload .msi assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.msi"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Extract .msi.sig File
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.msi\\.sig"  # Valid regex pattern
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload .msi.sig assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.msi.sig"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Extract .app.tar.gz Files
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.app\\.tar\\.gz"  # Valid regex pattern
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload .app.tar.gz assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.app.tar.gz"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Extract .app.tar.gz.sig Files
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.app\\.tar\\.gz\\.sig"  # Valid regex pattern
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload .app.tar.gz.sig assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.app.tar.gz.sig"
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
