name: Release artifacts from Querent Production repository

on:
  push:
    tags:
      - "v*"

jobs:
  release-querent-binary-artifacts:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-apple-darwin,
            aarch64-apple-darwin,
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc.exe,
          ]

    steps:
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo "ASSET_FULL_NAME=rian-${{ env.ASSET_VERSION }}-${{ matrix.target }}" >> $GITHUB_ENV
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          target: ${{ env.ASSET_FULL_NAME }}.tar.gz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Upload binaries assets to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.ASSET_FULL_NAME }}.tar.gz
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}

  release-querent-rian-installers:
    name: Release Linux, MacOs, Windows Installers
    runs-on: ubuntu-latest
    steps:
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Download Windows Installer(s)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.msi"
          target: "rian/"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Download Linux Installer(s)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.AppImage"
          target: "rian/"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Download MacOS Installer(s)
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.tar.gz"
          target: "rian/"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Download All .sig files
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: ".*\\.sig"
          target: "rian/"
          regex: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Download update.json
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "querent-ai/querent"
          version: "tags/${{ env.ASSET_VERSION }}"
          file: "update.json"
          target: "rian/update.json"
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: LS rian/
        run: ls rian/
      - name: Upload Windows MSI to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: rian/*.msi
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Upload Linux AppImages to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: rian/*.AppImage
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Upload MacOS Binaries to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: rian/*.tar.gz
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Upload Signature Files to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: rian/*.sig
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
      - name: Upload update.json to GitHub Release
        uses: quickwit-inc/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: rian/update.json
          overwrite: true
          tag_name: ${{ env.ASSET_VERSION }}
